language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show urbansim
  # - conda: cytoolz jinja2 osmnet

before_script:
  - git clone https://github.com/udst/sanfran_urbansim.git
  - cd sanfran_urbansim; jupyter nbconvert --to python Simulation.ipynb
  - cd ..

script:
  - pycodestyle urbansim scripts
  - py.test --cov urbansim --cov-report term-missing
  - cd sanfran_urbansim; python Simulation.py
  - cd ..

after_success:
  - coveralls
  - bin/build_docs.sh

env:
  global:
  - secure: c2olC+qzN1VHJZlznPy7mUtRvAyU7I2C7N3sYkv71Ds+dx5WN8InF6mpwNs/ZKfERbbA9slSVmYjB4j2c+VT8S1J33o6aI4F4hWNr6l7DgBKoPmozvaDx0GQ45hMOeSHSG5OF+DZCSTEXtxQK82uj61sCvZ6dIlDOqRvAHCjQDI=
