language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show urbansim

before_script:
  - git clone https://github.com/udst/sanfran_urbansim.git
  - cd sanfran_urbansim; jupyter nbconvert --to python Simulation.ipynb
  - cd ..

script:
  - pycodestyle --max-line-length=100 urbansim
  - py.test --cov urbansim --cov-report term-missing
  - cd sanfran_urbansim; python Simulation.py
  - cd ..

after_success:
  - coveralls
