language: python
sudo: false
python:
- '2.7'
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
- >
  conda create -q -c synthicity -n test-environment
  python=$TRAVIS_PYTHON_VERSION
  ipython-notebook jinja2 matplotlib numpy pandas patsy pip scipy statsmodels
  pandana pytables pytest pyyaml toolz
- source activate test-environment
- pip install simplejson bottle
- pip install pytest-cov coveralls pep8
- pip install .
before_script:
- git clone https://github.com/synthicity/sanfran_urbansim.git
- cd sanfran_urbansim; ipython nbconvert --to python Simulation.ipynb
- cd ..
script:
- pep8 urbansim scripts
- py.test --cov urbansim --cov-report term-missing
- cd sanfran_urbansim; python Simulation.py
- cd ..
after_success:
- coveralls
- bin/build_docs.sh
notifications:
  slack:
    secure: "JZol2I53hqYOKMZYBTpgePpWXX8Kv8HfmcM7GhcBybef9yBdLkKh3FKdk9N0yAipE1lGz8sTgE3H0/d457MPbTEgE/01Tel+J27H7xq0usBWO+z3pqIzHFTVKQ0ohPo6GYukzjrmw646FQqJSgIpuN30CLmgGVAQlAAZQfJE+zY="
env:
  global:
  - secure: c2olC+qzN1VHJZlznPy7mUtRvAyU7I2C7N3sYkv71Ds+dx5WN8InF6mpwNs/ZKfERbbA9slSVmYjB4j2c+VT8S1J33o6aI4F4hWNr6l7DgBKoPmozvaDx0GQ45hMOeSHSG5OF+DZCSTEXtxQK82uj61sCvZ6dIlDOqRvAHCjQDI=

